spring:
  application:
    name: euraka-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8176/eureka/,http://127.0.0.1:8177/eureka/
    register-with-eureka: false
  server:
    enable-self-preservation: false
server:
  port: 8176
